name             'nbs-wikipedia'
maintainer       'JD Harrington'
maintainer_email 'jd@jdharrington.net'
license          'all_rights'
description      'Installs/Configures nbs-wikipedia'
long_description 'Installs/Configures nbs-wikipedia'
version          '0.1.0'

depends 'apt',    '~> 2.6.0'
depends 'hadoop', '~> 1.5.0'
depends 'java',   '~> 1.28.0'
